// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartBell.Api.Data.DbContext;

#nullable disable

namespace SmartBell.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104191334_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartBell.Api.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SmartBell.Api.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Adults")
                        .HasColumnType("integer");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date");

                    b.Property<int>("ChildrenUnder12")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoomPreference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("RoomTypeSnapshot")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("SmartBell.Api.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amenities")
                        .HasColumnType("integer");

                    b.Property<decimal>("BasePricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Preference")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6587111d-0d30-4619-bc77-122f42793c57"),
                            Amenities = 0,
                            BasePricePerNight = 120m,
                            Capacity = 2,
                            Code = "A-101",
                            Preference = "TypeA_2PersonSuite",
                            Status = "Active",
                            Type = "Type A - 2-Person Suite"
                        },
                        new
                        {
                            Id = new Guid("ff007465-cb35-455c-80a8-747f1cdef6a2"),
                            Amenities = 0,
                            BasePricePerNight = 150m,
                            Capacity = 3,
                            Code = "B-201",
                            Preference = "TypeB_3PersonSuite",
                            Status = "Active",
                            Type = "Type B - 3-Person Suite"
                        },
                        new
                        {
                            Id = new Guid("5ea50d27-46b0-4147-9c29-2e93e3064c02"),
                            Amenities = 0,
                            BasePricePerNight = 180m,
                            Capacity = 4,
                            Code = "C-301",
                            Preference = "TypeC_4PersonFamilySuite",
                            Status = "Active",
                            Type = "Type C - 4-Person Family Suite"
                        },
                        new
                        {
                            Id = new Guid("576d6c6b-7007-426c-9bdd-d1fecb1e102a"),
                            Amenities = 0,
                            BasePricePerNight = 200m,
                            Capacity = 5,
                            Code = "D-401",
                            Preference = "TypeD_5PersonGrandSuite",
                            Status = "Active",
                            Type = "Type D - 5-Person Grand Suite"
                        },
                        new
                        {
                            Id = new Guid("cdf67845-cc40-447f-afd4-817a81e4d7e4"),
                            Amenities = 1,
                            BasePricePerNight = 220m,
                            Capacity = 2,
                            Code = "J-501",
                            Preference = "PrivateJacuzzi",
                            Status = "Active",
                            Type = "Rooms with Private Jacuzzi"
                        },
                        new
                        {
                            Id = new Guid("ca7ea75f-751e-443e-8bc5-b9dd792e93c1"),
                            Amenities = 2,
                            BasePricePerNight = 250m,
                            Capacity = 2,
                            Code = "P-601",
                            Preference = "InfinityPool",
                            Status = "Active",
                            Type = "Rooms with Infinity Pool"
                        },
                        new
                        {
                            Id = new Guid("a293450f-39d6-4876-9cfa-d46262582388"),
                            Amenities = 3,
                            BasePricePerNight = 280m,
                            Capacity = 3,
                            Code = "PS-701",
                            Preference = "PremiumSuites",
                            Status = "Active",
                            Type = "Premium Suites (Jacuzzi + Pool)"
                        });
                });

            modelBuilder.Entity("SmartBell.Api.Domain.Entities.Payment", b =>
                {
                    b.HasOne("SmartBell.Api.Domain.Entities.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SmartBell.Api.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("SmartBell.Api.Domain.Entities.Room", null)
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("SmartBell.Api.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SmartBell.Api.Domain.Entities.Room", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
